// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: identity.proto

package dmcnpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VerificationTier represents the level of identity verification.
// See whitepaper Section 15.2.2.
type VerificationTier int32

const (
	VerificationTier_VERIFICATION_TIER_UNVERIFIED      VerificationTier = 0
	VerificationTier_VERIFICATION_TIER_PROVIDER_HOSTED VerificationTier = 1
	VerificationTier_VERIFICATION_TIER_DOMAIN_DNS      VerificationTier = 2
	VerificationTier_VERIFICATION_TIER_DANE            VerificationTier = 3
)

// Enum value maps for VerificationTier.
var (
	VerificationTier_name = map[int32]string{
		0: "VERIFICATION_TIER_UNVERIFIED",
		1: "VERIFICATION_TIER_PROVIDER_HOSTED",
		2: "VERIFICATION_TIER_DOMAIN_DNS",
		3: "VERIFICATION_TIER_DANE",
	}
	VerificationTier_value = map[string]int32{
		"VERIFICATION_TIER_UNVERIFIED":      0,
		"VERIFICATION_TIER_PROVIDER_HOSTED": 1,
		"VERIFICATION_TIER_DOMAIN_DNS":      2,
		"VERIFICATION_TIER_DANE":            3,
	}
)

func (x VerificationTier) Enum() *VerificationTier {
	p := new(VerificationTier)
	*p = x
	return p
}

func (x VerificationTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerificationTier) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_proto_enumTypes[0].Descriptor()
}

func (VerificationTier) Type() protoreflect.EnumType {
	return &file_identity_proto_enumTypes[0]
}

func (x VerificationTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerificationTier.Descriptor instead.
func (VerificationTier) EnumDescriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{0}
}

// AttestationType represents the method of attestation.
// See whitepaper Section 15.2.3.
type AttestationType int32

const (
	AttestationType_ATTESTATION_TYPE_UNSPECIFIED    AttestationType = 0
	AttestationType_ATTESTATION_TYPE_IN_PERSON      AttestationType = 1
	AttestationType_ATTESTATION_TYPE_FINGERPRINT    AttestationType = 2
	AttestationType_ATTESTATION_TYPE_NETWORK        AttestationType = 3
	AttestationType_ATTESTATION_TYPE_ORGANISATIONAL AttestationType = 4
)

// Enum value maps for AttestationType.
var (
	AttestationType_name = map[int32]string{
		0: "ATTESTATION_TYPE_UNSPECIFIED",
		1: "ATTESTATION_TYPE_IN_PERSON",
		2: "ATTESTATION_TYPE_FINGERPRINT",
		3: "ATTESTATION_TYPE_NETWORK",
		4: "ATTESTATION_TYPE_ORGANISATIONAL",
	}
	AttestationType_value = map[string]int32{
		"ATTESTATION_TYPE_UNSPECIFIED":    0,
		"ATTESTATION_TYPE_IN_PERSON":      1,
		"ATTESTATION_TYPE_FINGERPRINT":    2,
		"ATTESTATION_TYPE_NETWORK":        3,
		"ATTESTATION_TYPE_ORGANISATIONAL": 4,
	}
)

func (x AttestationType) Enum() *AttestationType {
	p := new(AttestationType)
	*p = x
	return p
}

func (x AttestationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttestationType) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_proto_enumTypes[1].Descriptor()
}

func (AttestationType) Type() protoreflect.EnumType {
	return &file_identity_proto_enumTypes[1]
}

func (x AttestationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttestationType.Descriptor instead.
func (AttestationType) EnumDescriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{1}
}

// AttestationRecord represents a web-of-trust attestation.
// See whitepaper Section 15.2.3.
type AttestationRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AttesterAddress string                 `protobuf:"bytes,1,opt,name=attester_address,json=attesterAddress,proto3" json:"attester_address,omitempty"`
	AttesterPubkey  []byte                 `protobuf:"bytes,2,opt,name=attester_pubkey,json=attesterPubkey,proto3" json:"attester_pubkey,omitempty"` // 32 bytes Ed25519
	SubjectAddress  string                 `protobuf:"bytes,3,opt,name=subject_address,json=subjectAddress,proto3" json:"subject_address,omitempty"`
	SubjectPubkey   []byte                 `protobuf:"bytes,4,opt,name=subject_pubkey,json=subjectPubkey,proto3" json:"subject_pubkey,omitempty"` // 32 bytes Ed25519
	AttestationType AttestationType        `protobuf:"varint,5,opt,name=attestation_type,json=attestationType,proto3,enum=dmcn.identity.AttestationType" json:"attestation_type,omitempty"`
	AttestedAt      int64                  `protobuf:"varint,6,opt,name=attested_at,json=attestedAt,proto3" json:"attested_at,omitempty"` // Unix seconds
	ExpiresAt       int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`    // Unix seconds; 0 = no expiry
	Signature       []byte                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`                      // 64 bytes Ed25519 sig over all preceding fields
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttestationRecord) Reset() {
	*x = AttestationRecord{}
	mi := &file_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationRecord) ProtoMessage() {}

func (x *AttestationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationRecord.ProtoReflect.Descriptor instead.
func (*AttestationRecord) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{0}
}

func (x *AttestationRecord) GetAttesterAddress() string {
	if x != nil {
		return x.AttesterAddress
	}
	return ""
}

func (x *AttestationRecord) GetAttesterPubkey() []byte {
	if x != nil {
		return x.AttesterPubkey
	}
	return nil
}

func (x *AttestationRecord) GetSubjectAddress() string {
	if x != nil {
		return x.SubjectAddress
	}
	return ""
}

func (x *AttestationRecord) GetSubjectPubkey() []byte {
	if x != nil {
		return x.SubjectPubkey
	}
	return nil
}

func (x *AttestationRecord) GetAttestationType() AttestationType {
	if x != nil {
		return x.AttestationType
	}
	return AttestationType_ATTESTATION_TYPE_UNSPECIFIED
}

func (x *AttestationRecord) GetAttestedAt() int64 {
	if x != nil {
		return x.AttestedAt
	}
	return 0
}

func (x *AttestationRecord) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *AttestationRecord) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// IdentityRecord is a self-certifying identity binding.
// See whitepaper Section 15.2.2.
type IdentityRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Address          string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                                             // local@domain
	Ed25519PublicKey []byte                 `protobuf:"bytes,3,opt,name=ed25519_public_key,json=ed25519PublicKey,proto3" json:"ed25519_public_key,omitempty"` // 32 bytes
	X25519PublicKey  []byte                 `protobuf:"bytes,4,opt,name=x25519_public_key,json=x25519PublicKey,proto3" json:"x25519_public_key,omitempty"`    // 32 bytes
	CreatedAt        int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                       // Unix seconds
	ExpiresAt        int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`                       // Unix seconds; 0 = no expiry
	RelayHints       []string               `protobuf:"bytes,7,rep,name=relay_hints,json=relayHints,proto3" json:"relay_hints,omitempty"`
	VerificationTier VerificationTier       `protobuf:"varint,8,opt,name=verification_tier,json=verificationTier,proto3,enum=dmcn.identity.VerificationTier" json:"verification_tier,omitempty"`
	Attestations     []*AttestationRecord   `protobuf:"bytes,9,rep,name=attestations,proto3" json:"attestations,omitempty"`
	SelfSignature    []byte                 `protobuf:"bytes,10,opt,name=self_signature,json=selfSignature,proto3" json:"self_signature,omitempty"`           // 64 bytes Ed25519 sig over all preceding fields
	BridgeCapability bool                   `protobuf:"varint,11,opt,name=bridge_capability,json=bridgeCapability,proto3" json:"bridge_capability,omitempty"` // true if this identity operates as a bridge node
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IdentityRecord) Reset() {
	*x = IdentityRecord{}
	mi := &file_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityRecord) ProtoMessage() {}

func (x *IdentityRecord) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityRecord.ProtoReflect.Descriptor instead.
func (*IdentityRecord) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{1}
}

func (x *IdentityRecord) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *IdentityRecord) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *IdentityRecord) GetEd25519PublicKey() []byte {
	if x != nil {
		return x.Ed25519PublicKey
	}
	return nil
}

func (x *IdentityRecord) GetX25519PublicKey() []byte {
	if x != nil {
		return x.X25519PublicKey
	}
	return nil
}

func (x *IdentityRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *IdentityRecord) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *IdentityRecord) GetRelayHints() []string {
	if x != nil {
		return x.RelayHints
	}
	return nil
}

func (x *IdentityRecord) GetVerificationTier() VerificationTier {
	if x != nil {
		return x.VerificationTier
	}
	return VerificationTier_VERIFICATION_TIER_UNVERIFIED
}

func (x *IdentityRecord) GetAttestations() []*AttestationRecord {
	if x != nil {
		return x.Attestations
	}
	return nil
}

func (x *IdentityRecord) GetSelfSignature() []byte {
	if x != nil {
		return x.SelfSignature
	}
	return nil
}

func (x *IdentityRecord) GetBridgeCapability() bool {
	if x != nil {
		return x.BridgeCapability
	}
	return false
}

var File_identity_proto protoreflect.FileDescriptor

const file_identity_proto_rawDesc = "" +
	"\n" +
	"\x0eidentity.proto\x12\rdmcn.identity\"\xe0\x02\n" +
	"\x11AttestationRecord\x12)\n" +
	"\x10attester_address\x18\x01 \x01(\tR\x0fattesterAddress\x12'\n" +
	"\x0fattester_pubkey\x18\x02 \x01(\fR\x0eattesterPubkey\x12'\n" +
	"\x0fsubject_address\x18\x03 \x01(\tR\x0esubjectAddress\x12%\n" +
	"\x0esubject_pubkey\x18\x04 \x01(\fR\rsubjectPubkey\x12I\n" +
	"\x10attestation_type\x18\x05 \x01(\x0e2\x1e.dmcn.identity.AttestationTypeR\x0fattestationType\x12\x1f\n" +
	"\vattested_at\x18\x06 \x01(\x03R\n" +
	"attestedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignature\"\xe5\x03\n" +
	"\x0eIdentityRecord\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12,\n" +
	"\x12ed25519_public_key\x18\x03 \x01(\fR\x10ed25519PublicKey\x12*\n" +
	"\x11x25519_public_key\x18\x04 \x01(\fR\x0fx25519PublicKey\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\x12\x1f\n" +
	"\vrelay_hints\x18\a \x03(\tR\n" +
	"relayHints\x12L\n" +
	"\x11verification_tier\x18\b \x01(\x0e2\x1f.dmcn.identity.VerificationTierR\x10verificationTier\x12D\n" +
	"\fattestations\x18\t \x03(\v2 .dmcn.identity.AttestationRecordR\fattestations\x12%\n" +
	"\x0eself_signature\x18\n" +
	" \x01(\fR\rselfSignature\x12+\n" +
	"\x11bridge_capability\x18\v \x01(\bR\x10bridgeCapability*\x99\x01\n" +
	"\x10VerificationTier\x12 \n" +
	"\x1cVERIFICATION_TIER_UNVERIFIED\x10\x00\x12%\n" +
	"!VERIFICATION_TIER_PROVIDER_HOSTED\x10\x01\x12 \n" +
	"\x1cVERIFICATION_TIER_DOMAIN_DNS\x10\x02\x12\x1a\n" +
	"\x16VERIFICATION_TIER_DANE\x10\x03*\xb8\x01\n" +
	"\x0fAttestationType\x12 \n" +
	"\x1cATTESTATION_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aATTESTATION_TYPE_IN_PERSON\x10\x01\x12 \n" +
	"\x1cATTESTATION_TYPE_FINGERPRINT\x10\x02\x12\x1c\n" +
	"\x18ATTESTATION_TYPE_NETWORK\x10\x03\x12#\n" +
	"\x1fATTESTATION_TYPE_ORGANISATIONAL\x10\x04B7Z5github.com/mertenvg/dmcn/internal/proto/dmcnpb;dmcnpbb\x06proto3"

var (
	file_identity_proto_rawDescOnce sync.Once
	file_identity_proto_rawDescData []byte
)

func file_identity_proto_rawDescGZIP() []byte {
	file_identity_proto_rawDescOnce.Do(func() {
		file_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)))
	})
	return file_identity_proto_rawDescData
}

var file_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_identity_proto_goTypes = []any{
	(VerificationTier)(0),     // 0: dmcn.identity.VerificationTier
	(AttestationType)(0),      // 1: dmcn.identity.AttestationType
	(*AttestationRecord)(nil), // 2: dmcn.identity.AttestationRecord
	(*IdentityRecord)(nil),    // 3: dmcn.identity.IdentityRecord
}
var file_identity_proto_depIdxs = []int32{
	1, // 0: dmcn.identity.AttestationRecord.attestation_type:type_name -> dmcn.identity.AttestationType
	0, // 1: dmcn.identity.IdentityRecord.verification_tier:type_name -> dmcn.identity.VerificationTier
	2, // 2: dmcn.identity.IdentityRecord.attestations:type_name -> dmcn.identity.AttestationRecord
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_identity_proto_init() }
func file_identity_proto_init() {
	if File_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_proto_goTypes,
		DependencyIndexes: file_identity_proto_depIdxs,
		EnumInfos:         file_identity_proto_enumTypes,
		MessageInfos:      file_identity_proto_msgTypes,
	}.Build()
	File_identity_proto = out.File
	file_identity_proto_goTypes = nil
	file_identity_proto_depIdxs = nil
}
