// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: message.proto

package dmcnpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageBody holds the content of a message.
// See whitepaper Section 15.3.1.
type MessageBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // MIME type, e.g. "text/plain"
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                            // UTF-8 encoded body text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBody) Reset() {
	*x = MessageBody{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBody) ProtoMessage() {}

func (x *MessageBody) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBody.ProtoReflect.Descriptor instead.
func (*MessageBody) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *MessageBody) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MessageBody) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// AttachmentRecord describes an attachment within a message.
// See whitepaper Section 15.3.1.
type AttachmentRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  []byte                 `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"` // 16 bytes UUID
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // MIME type
	SizeBytes     uint64                 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentHash   []byte                 `protobuf:"bytes,5,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"` // 32 bytes SHA-256 of plaintext content
	Content       []byte                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                            // attachment content (encrypted separately)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentRecord) Reset() {
	*x = AttachmentRecord{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentRecord) ProtoMessage() {}

func (x *AttachmentRecord) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentRecord.ProtoReflect.Descriptor instead.
func (*AttachmentRecord) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *AttachmentRecord) GetAttachmentId() []byte {
	if x != nil {
		return x.AttachmentId
	}
	return nil
}

func (x *AttachmentRecord) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AttachmentRecord) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AttachmentRecord) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *AttachmentRecord) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *AttachmentRecord) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// PlaintextMessage represents a composed message before signing or encryption.
// See whitepaper Section 15.3.1.
type PlaintextMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	MessageId        []byte                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // 16 bytes UUID
	ThreadId         []byte                 `protobuf:"bytes,3,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`    // 16 bytes UUID
	SenderAddress    string                 `protobuf:"bytes,4,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	SenderPublicKey  []byte                 `protobuf:"bytes,5,opt,name=sender_public_key,json=senderPublicKey,proto3" json:"sender_public_key,omitempty"` // 32 bytes Ed25519
	RecipientAddress string                 `protobuf:"bytes,6,opt,name=recipient_address,json=recipientAddress,proto3" json:"recipient_address,omitempty"`
	SentAt           int64                  `protobuf:"varint,7,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"` // Unix seconds
	Subject          string                 `protobuf:"bytes,8,opt,name=subject,proto3" json:"subject,omitempty"`
	Body             *MessageBody           `protobuf:"bytes,9,opt,name=body,proto3" json:"body,omitempty"`
	Attachments      []*AttachmentRecord    `protobuf:"bytes,10,rep,name=attachments,proto3" json:"attachments,omitempty"`
	ReplyToId        []byte                 `protobuf:"bytes,11,opt,name=reply_to_id,json=replyToId,proto3" json:"reply_to_id,omitempty"` // 16 bytes UUID; empty = not a reply
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlaintextMessage) Reset() {
	*x = PlaintextMessage{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaintextMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaintextMessage) ProtoMessage() {}

func (x *PlaintextMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaintextMessage.ProtoReflect.Descriptor instead.
func (*PlaintextMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *PlaintextMessage) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PlaintextMessage) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *PlaintextMessage) GetThreadId() []byte {
	if x != nil {
		return x.ThreadId
	}
	return nil
}

func (x *PlaintextMessage) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *PlaintextMessage) GetSenderPublicKey() []byte {
	if x != nil {
		return x.SenderPublicKey
	}
	return nil
}

func (x *PlaintextMessage) GetRecipientAddress() string {
	if x != nil {
		return x.RecipientAddress
	}
	return ""
}

func (x *PlaintextMessage) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

func (x *PlaintextMessage) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PlaintextMessage) GetBody() *MessageBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PlaintextMessage) GetAttachments() []*AttachmentRecord {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *PlaintextMessage) GetReplyToId() []byte {
	if x != nil {
		return x.ReplyToId
	}
	return nil
}

// SignedMessage wraps a PlaintextMessage with the sender's Ed25519 signature.
// See whitepaper Section 15.3.2.
type SignedMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Plaintext       *PlaintextMessage      `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	SenderSignature []byte                 `protobuf:"bytes,2,opt,name=sender_signature,json=senderSignature,proto3" json:"sender_signature,omitempty"` // 64 bytes Ed25519 sig over canonical serialization of plaintext
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignedMessage) Reset() {
	*x = SignedMessage{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedMessage) ProtoMessage() {}

func (x *SignedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedMessage.ProtoReflect.Descriptor instead.
func (*SignedMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *SignedMessage) GetPlaintext() *PlaintextMessage {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *SignedMessage) GetSenderSignature() []byte {
	if x != nil {
		return x.SenderSignature
	}
	return nil
}

// RecipientRecord holds the wrapped CEK for a single recipient device.
// See whitepaper Section 15.3.3.
type RecipientRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      []byte                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                  // 16 bytes UUID
	RecipientXPub []byte                 `protobuf:"bytes,2,opt,name=recipient_x_pub,json=recipientXPub,proto3" json:"recipient_x_pub,omitempty"` // 32 bytes X25519 public key of recipient
	EphemeralXPub []byte                 `protobuf:"bytes,3,opt,name=ephemeral_x_pub,json=ephemeralXPub,proto3" json:"ephemeral_x_pub,omitempty"` // 32 bytes per-recipient ephemeral X25519 public key
	WrappedCek    []byte                 `protobuf:"bytes,4,opt,name=wrapped_cek,json=wrappedCek,proto3" json:"wrapped_cek,omitempty"`            // AES-256-GCM ciphertext of CEK
	CekNonce      []byte                 `protobuf:"bytes,5,opt,name=cek_nonce,json=cekNonce,proto3" json:"cek_nonce,omitempty"`                  // 12 bytes nonce for CEK wrapping
	CekTag        []byte                 `protobuf:"bytes,6,opt,name=cek_tag,json=cekTag,proto3" json:"cek_tag,omitempty"`                        // 16 bytes GCM auth tag for CEK wrapping
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipientRecord) Reset() {
	*x = RecipientRecord{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipientRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipientRecord) ProtoMessage() {}

func (x *RecipientRecord) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipientRecord.ProtoReflect.Descriptor instead.
func (*RecipientRecord) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *RecipientRecord) GetDeviceId() []byte {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

func (x *RecipientRecord) GetRecipientXPub() []byte {
	if x != nil {
		return x.RecipientXPub
	}
	return nil
}

func (x *RecipientRecord) GetEphemeralXPub() []byte {
	if x != nil {
		return x.EphemeralXPub
	}
	return nil
}

func (x *RecipientRecord) GetWrappedCek() []byte {
	if x != nil {
		return x.WrappedCek
	}
	return nil
}

func (x *RecipientRecord) GetCekNonce() []byte {
	if x != nil {
		return x.CekNonce
	}
	return nil
}

func (x *RecipientRecord) GetCekTag() []byte {
	if x != nil {
		return x.CekTag
	}
	return nil
}

// EncryptedEnvelope is the outer transport structure for encrypted messages.
// See whitepaper Section 15.3.3.
type EncryptedEnvelope struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	MessageId        []byte                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // 16 bytes UUID
	Recipients       []*RecipientRecord     `protobuf:"bytes,3,rep,name=recipients,proto3" json:"recipients,omitempty"`
	EncryptedPayload []byte                 `protobuf:"bytes,4,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`    // AES-256-GCM ciphertext of SignedMessage
	PayloadNonce     []byte                 `protobuf:"bytes,5,opt,name=payload_nonce,json=payloadNonce,proto3" json:"payload_nonce,omitempty"`                // 12 bytes nonce for payload encryption
	PayloadTag       []byte                 `protobuf:"bytes,6,opt,name=payload_tag,json=payloadTag,proto3" json:"payload_tag,omitempty"`                      // 16 bytes GCM auth tag for payload
	PayloadSizeClass uint32                 `protobuf:"varint,7,opt,name=payload_size_class,json=payloadSizeClass,proto3" json:"payload_size_class,omitempty"` // padded size bucket
	CreatedAt        int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                        // Unix seconds
	RatchetPubKey    []byte                 `protobuf:"bytes,9,opt,name=ratchet_pub_key,json=ratchetPubKey,proto3" json:"ratchet_pub_key,omitempty"`           // 32 bytes; zero in protocol v1
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EncryptedEnvelope) Reset() {
	*x = EncryptedEnvelope{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedEnvelope) ProtoMessage() {}

func (x *EncryptedEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedEnvelope.ProtoReflect.Descriptor instead.
func (*EncryptedEnvelope) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *EncryptedEnvelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EncryptedEnvelope) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *EncryptedEnvelope) GetRecipients() []*RecipientRecord {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *EncryptedEnvelope) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *EncryptedEnvelope) GetPayloadNonce() []byte {
	if x != nil {
		return x.PayloadNonce
	}
	return nil
}

func (x *EncryptedEnvelope) GetPayloadTag() []byte {
	if x != nil {
		return x.PayloadTag
	}
	return nil
}

func (x *EncryptedEnvelope) GetPayloadSizeClass() uint32 {
	if x != nil {
		return x.PayloadSizeClass
	}
	return 0
}

func (x *EncryptedEnvelope) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *EncryptedEnvelope) GetRatchetPubKey() []byte {
	if x != nil {
		return x.RatchetPubKey
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\fdmcn.message\"J\n" +
	"\vMessageBody\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\xd2\x01\n" +
	"\x10AttachmentRecord\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\fR\fattachmentId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\x12!\n" +
	"\fcontent_hash\x18\x05 \x01(\fR\vcontentHash\x12\x18\n" +
	"\acontent\x18\x06 \x01(\fR\acontent\"\xac\x03\n" +
	"\x10PlaintextMessage\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\fR\tmessageId\x12\x1b\n" +
	"\tthread_id\x18\x03 \x01(\fR\bthreadId\x12%\n" +
	"\x0esender_address\x18\x04 \x01(\tR\rsenderAddress\x12*\n" +
	"\x11sender_public_key\x18\x05 \x01(\fR\x0fsenderPublicKey\x12+\n" +
	"\x11recipient_address\x18\x06 \x01(\tR\x10recipientAddress\x12\x17\n" +
	"\asent_at\x18\a \x01(\x03R\x06sentAt\x12\x18\n" +
	"\asubject\x18\b \x01(\tR\asubject\x12-\n" +
	"\x04body\x18\t \x01(\v2\x19.dmcn.message.MessageBodyR\x04body\x12@\n" +
	"\vattachments\x18\n" +
	" \x03(\v2\x1e.dmcn.message.AttachmentRecordR\vattachments\x12\x1e\n" +
	"\vreply_to_id\x18\v \x01(\fR\treplyToId\"x\n" +
	"\rSignedMessage\x12<\n" +
	"\tplaintext\x18\x01 \x01(\v2\x1e.dmcn.message.PlaintextMessageR\tplaintext\x12)\n" +
	"\x10sender_signature\x18\x02 \x01(\fR\x0fsenderSignature\"\xd5\x01\n" +
	"\x0fRecipientRecord\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\fR\bdeviceId\x12&\n" +
	"\x0frecipient_x_pub\x18\x02 \x01(\fR\rrecipientXPub\x12&\n" +
	"\x0fephemeral_x_pub\x18\x03 \x01(\fR\rephemeralXPub\x12\x1f\n" +
	"\vwrapped_cek\x18\x04 \x01(\fR\n" +
	"wrappedCek\x12\x1b\n" +
	"\tcek_nonce\x18\x05 \x01(\fR\bcekNonce\x12\x17\n" +
	"\acek_tag\x18\x06 \x01(\fR\x06cekTag\"\xf3\x02\n" +
	"\x11EncryptedEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\fR\tmessageId\x12=\n" +
	"\n" +
	"recipients\x18\x03 \x03(\v2\x1d.dmcn.message.RecipientRecordR\n" +
	"recipients\x12+\n" +
	"\x11encrypted_payload\x18\x04 \x01(\fR\x10encryptedPayload\x12#\n" +
	"\rpayload_nonce\x18\x05 \x01(\fR\fpayloadNonce\x12\x1f\n" +
	"\vpayload_tag\x18\x06 \x01(\fR\n" +
	"payloadTag\x12,\n" +
	"\x12payload_size_class\x18\a \x01(\rR\x10payloadSizeClass\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12&\n" +
	"\x0fratchet_pub_key\x18\t \x01(\fR\rratchetPubKeyB7Z5github.com/mertenvg/dmcn/internal/proto/dmcnpb;dmcnpbb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_message_proto_goTypes = []any{
	(*MessageBody)(nil),       // 0: dmcn.message.MessageBody
	(*AttachmentRecord)(nil),  // 1: dmcn.message.AttachmentRecord
	(*PlaintextMessage)(nil),  // 2: dmcn.message.PlaintextMessage
	(*SignedMessage)(nil),     // 3: dmcn.message.SignedMessage
	(*RecipientRecord)(nil),   // 4: dmcn.message.RecipientRecord
	(*EncryptedEnvelope)(nil), // 5: dmcn.message.EncryptedEnvelope
}
var file_message_proto_depIdxs = []int32{
	0, // 0: dmcn.message.PlaintextMessage.body:type_name -> dmcn.message.MessageBody
	1, // 1: dmcn.message.PlaintextMessage.attachments:type_name -> dmcn.message.AttachmentRecord
	2, // 2: dmcn.message.SignedMessage.plaintext:type_name -> dmcn.message.PlaintextMessage
	4, // 3: dmcn.message.EncryptedEnvelope.recipients:type_name -> dmcn.message.RecipientRecord
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
