// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: relay.proto

package dmcnpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RelayRequest is the top-level request wrapper for relay protocol operations.
// Sent over libp2p streams using length-prefixed protobuf encoding.
type RelayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*RelayRequest_Store
	//	*RelayRequest_FetchInit
	//	*RelayRequest_FetchProof
	//	*RelayRequest_Ack
	//	*RelayRequest_Ping
	Request       isRelayRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayRequest) Reset() {
	*x = RelayRequest{}
	mi := &file_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRequest) ProtoMessage() {}

func (x *RelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRequest.ProtoReflect.Descriptor instead.
func (*RelayRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0}
}

func (x *RelayRequest) GetRequest() isRelayRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RelayRequest) GetStore() *StoreRequest {
	if x != nil {
		if x, ok := x.Request.(*RelayRequest_Store); ok {
			return x.Store
		}
	}
	return nil
}

func (x *RelayRequest) GetFetchInit() *FetchInit {
	if x != nil {
		if x, ok := x.Request.(*RelayRequest_FetchInit); ok {
			return x.FetchInit
		}
	}
	return nil
}

func (x *RelayRequest) GetFetchProof() *FetchProof {
	if x != nil {
		if x, ok := x.Request.(*RelayRequest_FetchProof); ok {
			return x.FetchProof
		}
	}
	return nil
}

func (x *RelayRequest) GetAck() *AckRequest {
	if x != nil {
		if x, ok := x.Request.(*RelayRequest_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *RelayRequest) GetPing() *PingRequest {
	if x != nil {
		if x, ok := x.Request.(*RelayRequest_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isRelayRequest_Request interface {
	isRelayRequest_Request()
}

type RelayRequest_Store struct {
	Store *StoreRequest `protobuf:"bytes,1,opt,name=store,proto3,oneof"`
}

type RelayRequest_FetchInit struct {
	FetchInit *FetchInit `protobuf:"bytes,2,opt,name=fetch_init,json=fetchInit,proto3,oneof"`
}

type RelayRequest_FetchProof struct {
	FetchProof *FetchProof `protobuf:"bytes,3,opt,name=fetch_proof,json=fetchProof,proto3,oneof"`
}

type RelayRequest_Ack struct {
	Ack *AckRequest `protobuf:"bytes,4,opt,name=ack,proto3,oneof"`
}

type RelayRequest_Ping struct {
	Ping *PingRequest `protobuf:"bytes,5,opt,name=ping,proto3,oneof"`
}

func (*RelayRequest_Store) isRelayRequest_Request() {}

func (*RelayRequest_FetchInit) isRelayRequest_Request() {}

func (*RelayRequest_FetchProof) isRelayRequest_Request() {}

func (*RelayRequest_Ack) isRelayRequest_Request() {}

func (*RelayRequest_Ping) isRelayRequest_Request() {}

// RelayResponse is the top-level response wrapper for relay protocol operations.
type RelayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*RelayResponse_Store
	//	*RelayResponse_FetchChallenge
	//	*RelayResponse_Fetch
	//	*RelayResponse_Ack
	//	*RelayResponse_Ping
	//	*RelayResponse_Error
	Response      isRelayResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayResponse) Reset() {
	*x = RelayResponse{}
	mi := &file_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayResponse) ProtoMessage() {}

func (x *RelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayResponse.ProtoReflect.Descriptor instead.
func (*RelayResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{1}
}

func (x *RelayResponse) GetResponse() isRelayResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *RelayResponse) GetStore() *StoreResponse {
	if x != nil {
		if x, ok := x.Response.(*RelayResponse_Store); ok {
			return x.Store
		}
	}
	return nil
}

func (x *RelayResponse) GetFetchChallenge() *FetchChallenge {
	if x != nil {
		if x, ok := x.Response.(*RelayResponse_FetchChallenge); ok {
			return x.FetchChallenge
		}
	}
	return nil
}

func (x *RelayResponse) GetFetch() *FetchResponse {
	if x != nil {
		if x, ok := x.Response.(*RelayResponse_Fetch); ok {
			return x.Fetch
		}
	}
	return nil
}

func (x *RelayResponse) GetAck() *AckResponse {
	if x != nil {
		if x, ok := x.Response.(*RelayResponse_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *RelayResponse) GetPing() *PingResponse {
	if x != nil {
		if x, ok := x.Response.(*RelayResponse_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *RelayResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Response.(*RelayResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isRelayResponse_Response interface {
	isRelayResponse_Response()
}

type RelayResponse_Store struct {
	Store *StoreResponse `protobuf:"bytes,1,opt,name=store,proto3,oneof"`
}

type RelayResponse_FetchChallenge struct {
	FetchChallenge *FetchChallenge `protobuf:"bytes,2,opt,name=fetch_challenge,json=fetchChallenge,proto3,oneof"`
}

type RelayResponse_Fetch struct {
	Fetch *FetchResponse `protobuf:"bytes,3,opt,name=fetch,proto3,oneof"`
}

type RelayResponse_Ack struct {
	Ack *AckResponse `protobuf:"bytes,4,opt,name=ack,proto3,oneof"`
}

type RelayResponse_Ping struct {
	Ping *PingResponse `protobuf:"bytes,5,opt,name=ping,proto3,oneof"`
}

type RelayResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

func (*RelayResponse_Store) isRelayResponse_Response() {}

func (*RelayResponse_FetchChallenge) isRelayResponse_Response() {}

func (*RelayResponse_Fetch) isRelayResponse_Response() {}

func (*RelayResponse_Ack) isRelayResponse_Response() {}

func (*RelayResponse_Ping) isRelayResponse_Response() {}

func (*RelayResponse_Error) isRelayResponse_Response() {}

// StoreRequest asks the relay to store an encrypted envelope for a recipient.
// The sender must be registered in the DHT registry.
type StoreRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SenderAddress   string                 `protobuf:"bytes,1,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	SenderSignature []byte                 `protobuf:"bytes,2,opt,name=sender_signature,json=senderSignature,proto3" json:"sender_signature,omitempty"` // Ed25519 signature over envelope hash
	Envelope        *EncryptedEnvelope     `protobuf:"bytes,3,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{2}
}

func (x *StoreRequest) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *StoreRequest) GetSenderSignature() []byte {
	if x != nil {
		return x.SenderSignature
	}
	return nil
}

func (x *StoreRequest) GetEnvelope() *EncryptedEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

// StoreResponse confirms successful storage.
type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvelopeHash  []byte                 `protobuf:"bytes,1,opt,name=envelope_hash,json=envelopeHash,proto3" json:"envelope_hash,omitempty"` // SHA-256 of serialized EncryptedEnvelope
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{3}
}

func (x *StoreResponse) GetEnvelopeHash() []byte {
	if x != nil {
		return x.EnvelopeHash
	}
	return nil
}

// FetchInit begins the FETCH authentication flow.
type FetchInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchInit) Reset() {
	*x = FetchInit{}
	mi := &file_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchInit) ProtoMessage() {}

func (x *FetchInit) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchInit.ProtoReflect.Descriptor instead.
func (*FetchInit) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{4}
}

func (x *FetchInit) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// FetchChallenge is sent by the server with a random nonce for the client to sign.
type FetchChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"` // 32 bytes random challenge
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchChallenge) Reset() {
	*x = FetchChallenge{}
	mi := &file_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchChallenge) ProtoMessage() {}

func (x *FetchChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchChallenge.ProtoReflect.Descriptor instead.
func (*FetchChallenge) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{5}
}

func (x *FetchChallenge) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

// FetchProof provides the signed challenge nonce to authenticate the recipient.
type FetchProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // Ed25519 signature over nonce
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchProof) Reset() {
	*x = FetchProof{}
	mi := &file_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchProof) ProtoMessage() {}

func (x *FetchProof) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchProof.ProtoReflect.Descriptor instead.
func (*FetchProof) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{6}
}

func (x *FetchProof) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *FetchProof) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *FetchProof) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// FetchResponse returns pending envelopes for the authenticated recipient.
type FetchResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Envelopes      []*EncryptedEnvelope   `protobuf:"bytes,1,rep,name=envelopes,proto3" json:"envelopes,omitempty"`
	EnvelopeHashes [][]byte               `protobuf:"bytes,2,rep,name=envelope_hashes,json=envelopeHashes,proto3" json:"envelope_hashes,omitempty"` // SHA-256 hashes corresponding to each envelope
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{7}
}

func (x *FetchResponse) GetEnvelopes() []*EncryptedEnvelope {
	if x != nil {
		return x.Envelopes
	}
	return nil
}

func (x *FetchResponse) GetEnvelopeHashes() [][]byte {
	if x != nil {
		return x.EnvelopeHashes
	}
	return nil
}

// AckRequest confirms successful decryption of an envelope.
type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvelopeHash  []byte                 `protobuf:"bytes,1,opt,name=envelope_hash,json=envelopeHash,proto3" json:"envelope_hash,omitempty"` // SHA-256 of the envelope being acknowledged
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_relay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{8}
}

func (x *AckRequest) GetEnvelopeHash() []byte {
	if x != nil {
		return x.EnvelopeHash
	}
	return nil
}

// AckResponse confirms the ACK was processed.
type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_relay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{9}
}

func (x *AckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// PingRequest is a liveness check.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_relay_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{10}
}

// PingResponse returns relay node metadata.
type PingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds   int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	StoredEnvelopes uint32                 `protobuf:"varint,3,opt,name=stored_envelopes,json=storedEnvelopes,proto3" json:"stored_envelopes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_relay_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{11}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *PingResponse) GetStoredEnvelopes() uint32 {
	if x != nil {
		return x.StoredEnvelopes
	}
	return 0
}

// ErrorResponse is returned when an operation fails.
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_relay_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{12}
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_relay_proto protoreflect.FileDescriptor

const file_relay_proto_rawDesc = "" +
	"\n" +
	"\vrelay.proto\x12\n" +
	"dmcn.relay\x1a\rmessage.proto\"\x99\x02\n" +
	"\fRelayRequest\x120\n" +
	"\x05store\x18\x01 \x01(\v2\x18.dmcn.relay.StoreRequestH\x00R\x05store\x126\n" +
	"\n" +
	"fetch_init\x18\x02 \x01(\v2\x15.dmcn.relay.FetchInitH\x00R\tfetchInit\x129\n" +
	"\vfetch_proof\x18\x03 \x01(\v2\x16.dmcn.relay.FetchProofH\x00R\n" +
	"fetchProof\x12*\n" +
	"\x03ack\x18\x04 \x01(\v2\x16.dmcn.relay.AckRequestH\x00R\x03ack\x12-\n" +
	"\x04ping\x18\x05 \x01(\v2\x17.dmcn.relay.PingRequestH\x00R\x04pingB\t\n" +
	"\arequest\"\xd8\x02\n" +
	"\rRelayResponse\x121\n" +
	"\x05store\x18\x01 \x01(\v2\x19.dmcn.relay.StoreResponseH\x00R\x05store\x12E\n" +
	"\x0ffetch_challenge\x18\x02 \x01(\v2\x1a.dmcn.relay.FetchChallengeH\x00R\x0efetchChallenge\x121\n" +
	"\x05fetch\x18\x03 \x01(\v2\x19.dmcn.relay.FetchResponseH\x00R\x05fetch\x12+\n" +
	"\x03ack\x18\x04 \x01(\v2\x17.dmcn.relay.AckResponseH\x00R\x03ack\x12.\n" +
	"\x04ping\x18\x05 \x01(\v2\x18.dmcn.relay.PingResponseH\x00R\x04ping\x121\n" +
	"\x05error\x18\x06 \x01(\v2\x19.dmcn.relay.ErrorResponseH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\x9d\x01\n" +
	"\fStoreRequest\x12%\n" +
	"\x0esender_address\x18\x01 \x01(\tR\rsenderAddress\x12)\n" +
	"\x10sender_signature\x18\x02 \x01(\fR\x0fsenderSignature\x12;\n" +
	"\benvelope\x18\x03 \x01(\v2\x1f.dmcn.message.EncryptedEnvelopeR\benvelope\"4\n" +
	"\rStoreResponse\x12#\n" +
	"\renvelope_hash\x18\x01 \x01(\fR\fenvelopeHash\"%\n" +
	"\tFetchInit\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"&\n" +
	"\x0eFetchChallenge\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\"Z\n" +
	"\n" +
	"FetchProof\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"w\n" +
	"\rFetchResponse\x12=\n" +
	"\tenvelopes\x18\x01 \x03(\v2\x1f.dmcn.message.EncryptedEnvelopeR\tenvelopes\x12'\n" +
	"\x0fenvelope_hashes\x18\x02 \x03(\fR\x0eenvelopeHashes\"1\n" +
	"\n" +
	"AckRequest\x12#\n" +
	"\renvelope_hash\x18\x01 \x01(\fR\fenvelopeHash\"'\n" +
	"\vAckResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\r\n" +
	"\vPingRequest\"z\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12)\n" +
	"\x10stored_envelopes\x18\x03 \x01(\rR\x0fstoredEnvelopes\"=\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB7Z5github.com/mertenvg/dmcn/internal/proto/dmcnpb;dmcnpbb\x06proto3"

var (
	file_relay_proto_rawDescOnce sync.Once
	file_relay_proto_rawDescData []byte
)

func file_relay_proto_rawDescGZIP() []byte {
	file_relay_proto_rawDescOnce.Do(func() {
		file_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)))
	})
	return file_relay_proto_rawDescData
}

var file_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_relay_proto_goTypes = []any{
	(*RelayRequest)(nil),      // 0: dmcn.relay.RelayRequest
	(*RelayResponse)(nil),     // 1: dmcn.relay.RelayResponse
	(*StoreRequest)(nil),      // 2: dmcn.relay.StoreRequest
	(*StoreResponse)(nil),     // 3: dmcn.relay.StoreResponse
	(*FetchInit)(nil),         // 4: dmcn.relay.FetchInit
	(*FetchChallenge)(nil),    // 5: dmcn.relay.FetchChallenge
	(*FetchProof)(nil),        // 6: dmcn.relay.FetchProof
	(*FetchResponse)(nil),     // 7: dmcn.relay.FetchResponse
	(*AckRequest)(nil),        // 8: dmcn.relay.AckRequest
	(*AckResponse)(nil),       // 9: dmcn.relay.AckResponse
	(*PingRequest)(nil),       // 10: dmcn.relay.PingRequest
	(*PingResponse)(nil),      // 11: dmcn.relay.PingResponse
	(*ErrorResponse)(nil),     // 12: dmcn.relay.ErrorResponse
	(*EncryptedEnvelope)(nil), // 13: dmcn.message.EncryptedEnvelope
}
var file_relay_proto_depIdxs = []int32{
	2,  // 0: dmcn.relay.RelayRequest.store:type_name -> dmcn.relay.StoreRequest
	4,  // 1: dmcn.relay.RelayRequest.fetch_init:type_name -> dmcn.relay.FetchInit
	6,  // 2: dmcn.relay.RelayRequest.fetch_proof:type_name -> dmcn.relay.FetchProof
	8,  // 3: dmcn.relay.RelayRequest.ack:type_name -> dmcn.relay.AckRequest
	10, // 4: dmcn.relay.RelayRequest.ping:type_name -> dmcn.relay.PingRequest
	3,  // 5: dmcn.relay.RelayResponse.store:type_name -> dmcn.relay.StoreResponse
	5,  // 6: dmcn.relay.RelayResponse.fetch_challenge:type_name -> dmcn.relay.FetchChallenge
	7,  // 7: dmcn.relay.RelayResponse.fetch:type_name -> dmcn.relay.FetchResponse
	9,  // 8: dmcn.relay.RelayResponse.ack:type_name -> dmcn.relay.AckResponse
	11, // 9: dmcn.relay.RelayResponse.ping:type_name -> dmcn.relay.PingResponse
	12, // 10: dmcn.relay.RelayResponse.error:type_name -> dmcn.relay.ErrorResponse
	13, // 11: dmcn.relay.StoreRequest.envelope:type_name -> dmcn.message.EncryptedEnvelope
	13, // 12: dmcn.relay.FetchResponse.envelopes:type_name -> dmcn.message.EncryptedEnvelope
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_relay_proto_init() }
func file_relay_proto_init() {
	if File_relay_proto != nil {
		return
	}
	file_message_proto_init()
	file_relay_proto_msgTypes[0].OneofWrappers = []any{
		(*RelayRequest_Store)(nil),
		(*RelayRequest_FetchInit)(nil),
		(*RelayRequest_FetchProof)(nil),
		(*RelayRequest_Ack)(nil),
		(*RelayRequest_Ping)(nil),
	}
	file_relay_proto_msgTypes[1].OneofWrappers = []any{
		(*RelayResponse_Store)(nil),
		(*RelayResponse_FetchChallenge)(nil),
		(*RelayResponse_Fetch)(nil),
		(*RelayResponse_Ack)(nil),
		(*RelayResponse_Ping)(nil),
		(*RelayResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relay_proto_goTypes,
		DependencyIndexes: file_relay_proto_depIdxs,
		MessageInfos:      file_relay_proto_msgTypes,
	}.Build()
	File_relay_proto = out.File
	file_relay_proto_goTypes = nil
	file_relay_proto_depIdxs = nil
}
